import { type NextPage } from "next";
import Head from "next/head";

const Pricing: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Pricing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main className="overflow-y-scroll h-screen overflow-x-hidden bg-gray-900">
        <section>
          <h1>Pricing</h1>
        </section>
      </main>
    </div>
  );
};

export default Pricing;